[program:apache]
command=/usr/sbin/apache2ctl -DFOREGROUND
autostart=true
autorestart=true
startretries=3
priority=100
stdout_logfile=/var/log/supervisor/apache-stdout.log
stderr_logfile=/var/log/supervisor/apache-stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
